splash = false

preload = ~/.config/backgrounds/light-mountains-blue.jpg
preload = ~/.config/backgrounds/dark-buildings.png

wallpaper {
    monitor = 
    path = ~/.config/backgrounds/dark-buildings.png
}

